import axios from 'axios';

const api = axios.create({
  baseURL: 'http://localhost:3636',
  timeout: 5000,
});

/**
 * Fetch all available courses and map categoryId to category name
 * If instructorId is provided, filter courses by instructor
 */
export const getCourses = async (instructorId = null) => {
  const [coursesRes, categoriesRes] = await Promise.all([
    api.get('/courses'),
    api.get('/categories'),
  ]);

  const categoryMap = new Map(
    categoriesRes.data.map((category) => [String(category.id), category.name])
  );

  let courses = coursesRes.data.map((course) => ({
    ...course,
    category: categoryMap.get(String(course.categoryId)) || 'Khác',
  }));

  // Filter by instructor if instructorId is provided
  if (instructorId) {
    courses = courses.filter((course) => course.instructorId === instructorId);
  }

  return { data: courses };
};

/**
 * Fetch all course categories and return as simple strings for the filter sidebar
 */
export const getCategories = async () => {
  const response = await api.get('/categories');
  return { data: response.data.map((category) => category.name) };
};

/**
 * Fetch all instructors
 */
export const getInstructors = async () => {
  return api.get('/instructors');
};

/**
 * Fetch all categories with full details
 */
export const getAllCategories = async () => {
  return api.get('/categories');
};

/**
 * Add a new category
 */
export const addCategory = async (name) => {
  return api.post('/categories', { name });
};

/**
 * Delete a category
 */
export const deleteCategory = async (id) => {
  return api.delete(`/categories/${id}`);
};

/**
 * Get courses by category ID
 */
export const getCoursesByCategory = async (categoryId) => {
  // Try both string and number for categoryId because the mock DB has mixed types
  const [resStr, resNum] = await Promise.all([
    api.get('/courses', { params: { categoryId: String(categoryId) } }),
    api.get('/courses', { params: { categoryId: Number(categoryId) } })
  ]);

  // Combine and remove duplicates
  const combined = [...resStr.data, ...resNum.data];
  const uniqueCourses = Array.from(new Set(combined.map(c => c.id)))
    .map(id => combined.find(c => c.id === id));

  return { data: uniqueCourses };
};

/**
 * Fetch a user profile by ID from json-server
 */
export const getUserProfile = async (userId) => {
  return api.get(`/users/${userId}`);
};

/**
 * Update a user profile using PATCH via json-server
 */
export const updateUserProfile = async (userId, userData) => {
  return api.patch(`/users/${userId}`, userData);
};

/**
 * Change a user's password using PATCH via json-server
 */
export const changePassword = async (userId, newPassword) => {
  return api.patch(`/users/${userId}`, { password: newPassword });
};

/**
 * Authentication: Login
 */
export const loginUser = async (email, password) => {
  try {
    // json-server 1.x blocks filtering by 'password' field via URL for security reasons.
    // So we fetch all users matching the email, then verify password on the client side.
    const response = await api.get('/users', { params: { email: email } });

    const user = response.data.find(
      u => u.email.toLowerCase() === email.toLowerCase() && u.password === password
    );

    return { data: user ? [user] : [] };
  } catch (error) {
    console.error("Login API Error:", error);
    throw error;
  }
};

/**
 * Authentication: Register
 */
export const registerUser = async (userData) => {
  try {
    // First check if email already exists
    const checkRes = await api.get(`/users?email=${userData.email}`);
    if (checkRes.data.length > 0) {
      throw new Error("Email đã được sử dụng bởi tài khoản khác.");
    }

    // ID will be auto-generated by json-server if not provided
    const response = await api.post('/users', {
      ...userData,
      role: 'student', // Default role
      avatar: `https://i.pravatar.cc/150?u=${userData.email}`, // Random avatar based on email
    });
    return response;
  } catch (error) {
    console.error("Register API Error:", error);
    throw error;
  }
};

/**
 * Update a course
 */
export const updateCourse = async (courseId, courseData) => {
  return api.put(`/courses/${courseId}`, courseData);
};

/**
 * Delete a course
 */
export const deleteCourse = async (courseId) => {
  return api.delete(`/courses/${courseId}`);
};

/**
 * Create a new course
 */
export const createCourse = async (courseData) => {
  return api.post('/courses', courseData);
};

/**
 * Get chapters in a course
 */
export const getChaptersByCourse = async (courseId) => {
  try {
    const [resStr, resNum] = await Promise.all([
      api.get('/chapters', { params: { courseId: String(courseId) } }),
      api.get('/chapters', { params: { courseId: Number(courseId) } })
    ]);

    const combined = [...resStr.data, ...resNum.data];
    const uniqueChapters = Array.from(new Set(combined.map((chapter) => chapter.id)))
      .map((id) => combined.find((chapter) => chapter.id === id));

    return { data: uniqueChapters };
  } catch (error) {
    if (error?.response?.status === 404) {
      return { data: [] };
    }

    throw error;
  }
};

/**
 * Get lessons by chapter list
 */
export const getLessonsByChapterIds = async (chapterIds = []) => {
  const response = await api.get('/lessons');
  const targetIds = chapterIds.map((id) => Number(id));
  const data = response.data.filter((lesson) =>
    targetIds.includes(Number(lesson.chapterId))
  );
  return { data };
};

/**
 * Get lessons by course ID
 */
export const getLessonsByCourseId = async (courseId) => {
  const [resStr, resNum] = await Promise.all([
    api.get('/lessons', { params: { courseId: String(courseId) } }),
    api.get('/lessons', { params: { courseId: Number(courseId) } })
  ]);

  const combined = [...resStr.data, ...resNum.data];
  const uniqueLessons = Array.from(new Set(combined.map((lesson) => lesson.id)))
    .map((id) => combined.find((lesson) => lesson.id === id));

  return { data: uniqueLessons };
};

/**
 * Create a lesson
 */
export const createLesson = async (lessonData) => {
  return api.post('/lessons', lessonData);
};

/**
 * Update a lesson
 */
export const updateLesson = async (lessonId, lessonData) => {
  return api.put(`/lessons/${lessonId}`, lessonData);
};

/**
 * Delete a lesson
 */
export const deleteLessonById = async (lessonId) => {
  return api.delete(`/lessons/${lessonId}`);
};
