import axios from 'axios';

const api = axios.create({
  baseURL: 'http://localhost:3636',
  timeout: 5000,
});

/**
 * Fetch all available courses and map categoryId to category name
 */
export const getCourses = async () => {
  const [coursesRes, categoriesRes] = await Promise.all([
    api.get('/courses'),
    api.get('/categories'),
  ]);

  const categoryMap = new Map(
    categoriesRes.data.map((category) => [String(category.id), category.name])
  );

  const normalizedCourses = coursesRes.data.map((course) => ({
    ...course,
    category: categoryMap.get(String(course.categoryId)) || 'Khác',
  }));

  return { data: normalizedCourses };
};

/**
 * Fetch all course categories and return as simple strings for the filter sidebar
 */
export const getCategories = async () => {
  const response = await api.get('/categories');
  return { data: response.data.map((category) => category.name) };
};

/**
 * Fetch a user profile by ID from json-server
 */
export const getUserProfile = async (userId) => {
  return api.get(`/users/${userId}`);
};

/**
 * Update a user profile using PATCH via json-server
 */
export const updateUserProfile = async (userId, userData) => {
  return api.patch(`/users/${userId}`, userData);
};

/**
 * Change a user's password using PATCH via json-server
 */
export const changePassword = async (userId, newPassword) => {
  return api.patch(`/users/${userId}`, { password: newPassword });
};

/**
 * Authentication: Login
 */
export const loginUser = async (email, password) => {
  try {
    // json-server 1.x blocks filtering by 'password' field via URL for security reasons.
    // So we fetch all users matching the email, then verify password on the client side.
    const response = await api.get('/users', { params: { email: email } });

    const user = response.data.find(
      u => u.email.toLowerCase() === email.toLowerCase() && u.password === password
    );

    return { data: user ? [user] : [] };
  } catch (error) {
    console.error("Login API Error:", error);
    throw error;
  }
};

/**
 * Authentication: Register
 */
export const registerUser = async (userData) => {
  try {
    // First check if email already exists
    const checkRes = await api.get(`/users?email=${userData.email}`);
    if (checkRes.data.length > 0) {
      throw new Error("Email đã được sử dụng bởi tài khoản khác.");
    }

    // ID will be auto-generated by json-server if not provided
    const response = await api.post('/users', {
      ...userData,
      role: 'student', // Default role
      avatar: `https://i.pravatar.cc/150?u=${userData.email}`, // Random avatar based on email
    });
    return response;
  } catch (error) {
    console.error("Register API Error:", error);
    throw error;
  }
};

/**
 * Update a course
 */
export const updateCourse = async (courseId, courseData) => {
  return api.put(`/courses/${courseId}`, courseData);
};

/**
 * Delete a course
 */
export const deleteCourse = async (courseId) => {
  return api.delete(`/courses/${courseId}`);
};

/**
 * Fetch all categories with full data (id, name)
 */
export const getAllCategories = async () => {
  return api.get('/categories');
};

/**
 * Fetch courses by categoryId
 */
export const getCoursesByCategory = async (categoryId) => {
  return api.get(`/courses?categoryId=${categoryId}`);
};

/**
 * Add a new category
 */
export const addCategory = async (categoryName) => {
  try {
    // Lấy toàn bộ danh mục hiện có để tìm ID lớn nhất
    const response = await api.get('/categories');
    const categories = response.data;

    let maxId = 0;
    categories.forEach(cat => {
      const numericId = parseInt(cat.id, 10);
      if (!isNaN(numericId) && numericId > maxId) {
        maxId = numericId;
      }
    });

    // Tăng ID lên 1
    const newId = String(maxId + 1);

    return await api.post('/categories', { id: newId, name: categoryName });
  } catch (error) {
    console.error("Lỗi khi tạo danh mục mới:", error);
    throw error;
  }
};
/**
 * Delete a category
 */
export const deleteCategory = async (categoryId) => {
  return api.delete(`/categories/${categoryId}`);
};
